runtime: nodejs18

env: standard

entrypoint: node_modules/.bin/next start

env_variables:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

vpc_access_connector:
  name: "projects/workcrew-revamped/locations/us-central1/connectors/default"

# Resources
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 20
